apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: realmytrip
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: realmytrip
  minReplicas: 1
  maxReplicas: 20
  targetCPUUtilizationPercentage: 50
