- hosts: k8s
  gather_facts: no
 
  tasks:
    - name: Destroy Deployment
      k8s:
        state: absent
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: realmytrip
            namespace: default
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: realmytrip
            template:
              metadata:
                labels:
                  app: realmytrip
              spec:
                containers:
                  - name: realmytrip
                    image: "ddung1203/realmytrip:{{ lookup('env', 'BUILD_NUMBER') }}"
                    imagePullPolicy: Always
                    ports:
                      - containerPort: 3000
                    resources:
                      requests:
                        cpu: 500m
                        memory: 500M
                      limits:
                        cpu: 800m
                        memory: 800M

    - name: Create Deployment
      k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: realmytrip
            namespace: default
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: realmytrip
            template:
              metadata:
                labels:
                  app: realmytrip
              spec:
                containers:
                  - name: realmytrip
                    image: "ddung1203/realmytrip:{{ lookup('env', 'BUILD_NUMBER') }}"
                    imagePullPolicy: Always
                    ports:
                      - containerPort: 3000
                    resources:
                      requests:
                        cpu: 500m
                        memory: 500M
                      limits:
                        cpu: 800m
                        memory: 800M

    - name: Create Service
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: realmytrip-lb
            namespace: default
            annotations:
             service.beta.kubernetes.io/aws-load-balancer-type: "external"
             service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "instance"
             service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
          spec:
            type: LoadBalancer
            selector:
              app: realmytrip
            ports:
              - port: 80
                targetPort: 3000

    - command: kubectl apply -f /home/vagrant/CICD_Project_Global_Website/realmytrip/playbook/hpa.yaml
